import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import { getBranding } from "@/services/branding/getBranding";

export async function buildInvoicePdf(
  invoice: any
) {

  const branding =
    await getBranding();

  const pdf =
    new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

  /*
  ================================================
  COMPANY HEADER
  ================================================
  */

  pdf.setFontSize(22);

  pdf.setTextColor(
    branding.primaryColor
  );

  pdf.text(

    branding.companyName,

    20,

    20

  );

  pdf.setFontSize(10);

  pdf.setTextColor(120);

  pdf.text(

    branding.address || "",

    20,

    27

  );

  pdf.text(

    branding.phone || "",

    20,

    32

  );

  pdf.text(

    branding.email || "",

    20,

    37

  );

  pdf.text(

    branding.website || "",

    20,

    42

  );

  /*
  ================================================
  TITLE
  ================================================
  */

  pdf.setFontSize(26);

  pdf.setTextColor(0);

  pdf.text(

    "INVOICE",

    150,

    20

  );

  /*
  ================================================
  INVOICE DETAILS
  ================================================
  */

  pdf.setFontSize(11);

  pdf.text(

    `Invoice No: ${invoice.invoice_number}`,

    20,

    60

  );

  pdf.text(

    `Billing Period: ${invoice.billing_period}`,

    20,

    67

  );

  pdf.text(

    `Issue Date: ${invoice.invoice_date}`,

    20,

    74

  );

  pdf.text(

    `Due Date: ${invoice.due_date}`,

    20,

    81

  );

  /*
  ================================================
  TENANT
  ================================================
  */

  pdf.setFontSize(14);

  pdf.text(

    "Bill To",

    20,

    98

  );

  pdf.setFontSize(11);

  pdf.text(

    invoice.tenant_name,

    20,

    105

  );

  pdf.text(

    invoice.property_name,

    20,

    111

  );

  pdf.text(

    `Unit ${invoice.unit_number}`,

    20,

    117

  );

  /*
  ================================================
  LINE ITEMS
  ================================================
  */

  autoTable(pdf, {

    startY: 128,

    head: [[

      "Description",

      "Qty",

      "Rate",

      "Amount",

    ]],

    body:

      invoice.items.map(

        (item: any) => [

          item.description,

          item.quantity,

          item.unit_price.toLocaleString(),

          item.amount.toLocaleString(),

        ]

      ),

  });

  const endY =
    (pdf as any)
      .lastAutoTable
      .finalY + 10;

  /*
  ================================================
  TOTALS
  ================================================
  */

  pdf.setFontSize(12);

  pdf.text(

    `Invoice Total: ${branding.currency} ${invoice.amount.toLocaleString()}`,

    120,

    endY

  );

  pdf.text(

    `Paid: ${branding.currency} ${invoice.amount_paid.toLocaleString()}`,

    120,

    endY + 8

  );

  pdf.setFontSize(15);

  pdf.text(

    `Balance: ${branding.currency} ${invoice.balance.toLocaleString()}`,

    120,

    endY + 18

  );

  /*
  ================================================
  FOOTER
  ================================================
  */

  pdf.setFontSize(9);

  pdf.setTextColor(120);

  pdf.text(

    "Generated by Ruby Rental",

    20,

    285

  );

  pdf.text(

    branding.slogan || "",

    20,

    290

  );

  return pdf;

}
